# comparisons
@_binary_comparison ==
@_binary_comparison !=
@_binary_comparison <
@_binary_comparison <=
@_binary_comparison >
@_binary_comparison >=
@_binary_comparison isapprox
@_unary_comparison iszero
@_unary_comparison isone
@_unary_comparison ispow2
@_unary_comparison isfinite
@_unary_comparison isnan
@_unary_comparison isinf
@_unary_comparison isinteger
@_unary_comparison iseven
@_unary_comparison isodd
@_unary_comparison issubnormal
